// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbwqayavgrhgkpgcmcul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZid3FheWF2Z3JoZ2twZ2NtY3VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1Nzc5MDQsImV4cCI6MjA2OTE1MzkwNH0.BNLjALO5NVJqPSNVDY5c0l-tP8BJ5mnX7fQu3OX10ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});